# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_ver: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_ver }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --remove-untracked
      - name: Lint with flake8
        run: |
          poetry run flake8 . --kwargs-inspect-module-extend functools,itertools --kwargs-ignore-function-pattern-extend ^pytest.mark.parametrize$
      - name: Type check with mypy
        run: |
          poetry run mypy -p flake8_force_keyword_arguments
      - name: Test with pytest
        run: |
          poetry run pytest tests --cov=./flake8_force_keyword_arguments --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
